### ISSUE TITLE
Adaptation

### ISSUE THREAD

**Issue by DayField** [indilo53/fivem-esx_phone#2]
Hello ! Primary, thank you for your amazing work !
I realy want this script but i use the jobs system with paycheck and the cops fiveM system. If you have the time, can you explain me what did i need to modify for a complete work with these scripts ? Or maybe just add a no dependance. Thanks

**Comment by indilo53** [comment]
Hello, Thank you :)

Hello, you can rework esx_phone to be dependent of essentialmode only. Just replace all the esx stuff with es one.

**Comment by indilo53** [comment]
esx:getPlayerFromId becomes es:getPlayerFromId for example

**Comment by DayField** [comment]
I ll try thank you

**Comment by iNoOx** [comment]
Salut Indilo, t'es vraiment une bête pour avoir coder ce téléphone ! ;)

Du coup c'est réellement ça ? J'ai juste à changer les esx: en  es: ? oO

**Comment by indilo53** [comment]
Oui à peux près il faut aussi recréer les notifications enfin la ou ca coince tu modifies le code.

**Comment by iNoOx** [comment]
Ouais, j'ai réussis à peu prêt à tout modifier, ça bloque juste quand la personne n'a pas de numéro, la fonction pour créer le numéro aléatoire fonctionne pas, ainsi que es:getPlayers lors de l'ajout de numéro (quand j'ai rentré le numéro à la main en bdd).. ._.
